### ISSUE TITLE
Doesn't auto-complete paths of exclusively vendored packages

### ISSUE THREAD

**Issue by cskr** [nsf/gocode#381] opened 2016-09-09 10:35 UTC
If a package is available only in the `vendor` directory and nowhere else in `GOPATH`, auto-complete for import paths does not include it.

**Comment by shackra** [comment] 2016-09-10 01:18
I'm experiencing this as well, and is driving me crazy...

**Comment by nsf** [comment] 2016-09-17 18:35
Also I summon @nhooyr, maybe he wants to fix the issue himself or has something to say here in general.

P.S. He's the author of import paths autocompletion.

**Comment by nhooyr** [comment] 2016-09-17 18:44
I'll fix this next weekend, shouldn't be too hard.

**Comment by shackra** [comment] 2016-09-17 19:48
Cool, thanks! 

El 17 de septiembre de 2016 12:44:08 GMT-06:00, Anmol Sethi <notifications@github.com> escribió:
>I'll fix this next weekend, shouldn't be too hard.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nsf/gocode/issues/381#issuecomment-247796817

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicorevin** [comment] 2016-10-12 22:17
@nsf @nhooyr next weekend is here. Maybe I could help you with it? Just need a little guidance in where to start digging.

**Comment by nsf** [comment] 2016-10-12 22:28
https://github.com/nsf/gocode/blob/master/declcache.go#L456-L487
https://github.com/nsf/gocode/blob/master/autocompletecontext.go#L231-L269

**Comment by nhooyr** [comment] 2016-10-12 22:44
I just reinstalled macOS Sierra and I have to set my dev environment again so unfortunately, I cannot help right now.

The exact function you need to modify is https://github.com/nsf/gocode/blob/master/autocompletecontext.go#L239-L269

**Comment by nicorevin** [comment] 2016-10-12 23:08
thanks guys! Dumb question: gocode does not care about pure source but about package objects under `pkg`, right?

**Comment by nhooyr** [comment] 2016-10-12 23:14
Yes.

**Comment by nicorevin** [comment] 2016-10-14 15:44
What I observe is:
<img width="578" alt="2016-10-14 18 35 51" src="https://cloud.githubusercontent.com/assets/2492836/19393452/70c9061c-923d-11e6-968d-a755bf86589e.png">
(neovim + vim-go). :/

Is this what you are experiencing as well?

**Comment by nhooyr** [comment] 2016-10-14 15:53
That is exactly what should be happening.

**Comment by shackra** [comment] 2016-10-14 16:29
Cutting the string until "vendor/" would make sense... 

El 14 de octubre de 2016 9:54:02 GMT-06:00, Anmol Sethi <notifications@github.com> escribió:
>That is exactly what should be happening.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nsf/gocode/issues/381#issuecomment-253841510

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nhooyr** [comment] 2016-10-14 18:33
@shackra of course, I was just saying that according to the current code, that is indeed the correct output.

**Comment by cskr** [comment] 2016-10-16 06:42
Doesn't work for me. Also, when trying to autocomplete `github` packages, I see packages from `9fans.net`, but not exclusively vendored packages. I don't know if this is a regression or an existing bug.

![gocode](https://cloud.githubusercontent.com/assets/173476/19415798/c0f2e542-9399-11e6-9025-d11f7847de6d.gif)

**Comment by nsf** [comment] 2016-10-16 08:12
Hm, I can't reproduce that bug of yours. Interesting.

**Comment by nsf** [comment] 2016-10-16 08:13
Can you paste output from `gocode -s -debug`? I.e. launch gocode manually via `gocode close` and then `gocode -s -debug` in a separate terminal window and then do your autocompletion and dump here what gocode prints.

**Comment by nsf** [comment] 2016-10-16 08:19
Oh, I think I know what happens. The added patch strips the path prefix up to "/vendor/", but it does so apparently after prefix filtering. As a result you might get irrelevant results. A bug definitely in @nicorevin implementation. Also the fact that he uses map for output is questionable, not sure if we sort output after that. Editors might sort it, but really gocode should also do it. I believe some plugins may rely on sorted order.

**Comment by nsf** [comment] 2016-10-16 08:24
Also it's questionable to include vendored packages of other libs. You can't import them directly! Only vendored packages of the currently edited package should be in that list.

**Comment by nicorevin** [comment] 2016-10-16 08:31
@nsf map is used to filter out duplicates before passing them to the `candidates` struct (see [this](https://github.com/nicorevin/gocode/blob/478b96fe0e77b4451b866559e2adb407fbce7120/autocompletecontext.go#L238-L240)).
As for vendored packages of other libs is there a way to determine what package I'm working on?
return of `9fans` is undesired of course... :(

**Comment by nsf** [comment] 2016-10-16 08:38
I understand why you're using map, all I'm saying is that map is not an ordered container. And if you use one, I think sorting the data afterwards would be nice. But that's a minor complaint.

As for current package name, yes. You can use `g_daemon.context.CurrentPackagePath`, but only in "go" package lookup mode.

**Comment by nsf** [comment] 2016-10-16 08:41
@nicorevin For sorting, never mind, gocode does sort autocompletion results before returning them.

**Comment by cskr** [comment] 2016-10-16 08:54
@nsf I'm only expecting directly vendored packages in auto-complete. This is the output of `go list ./...`:

```
go.thecskr.in/foo
go.thecskr.in/foo/vendor/github.com/boltdb/bolt
go.thecskr.in/foo/vendor/golang.org/x/sys/unix
```

I don't know whether it is still required, but here is the output of `gocode -s -debug`:

```
2016/10/16 14:21:34 Go project path: go.thecskr.in/foo
2016/10/16 14:21:34 Got autocompletion request for '$HOME/gopkgs/src/go.thecskr.in/foo/foo.go'
2016/10/16 14:21:34 Cursor at: 38
2016/10/16 14:21:34 -------------------------------------------------------
package main

import (
	"fmt"
	"github#
)

func main() {
	fmt.Println("vim-go")
}
2016/10/16 14:21:34 -------------------------------------------------------
2016/10/16 14:21:34 Error parsing input file (outer block):
2016/10/16 14:21:34  5:2: invalid import path: "github;
2016/10/16 14:21:34  5:2: string literal not terminated
2016/10/16 14:21:34 Found "fmt" at "$HOME/tools/go/pkg/linux_amd64/fmt.a"
2016/10/16 14:21:34 Import path "github" was not resolved
2016/10/16 14:21:34 Gocode's build context is:
2016/10/16 14:21:34  GOROOT: $HOME/tools/go
2016/10/16 14:21:34  GOPATH: $HOME/gopkgs
2016/10/16 14:21:34  GOOS: linux
2016/10/16 14:21:34  GOARCH: amd64
2016/10/16 14:21:34  BzlProjectRoot: ""
2016/10/16 14:21:34  GBProjectRoot: ""
2016/10/16 14:21:34  lib-path: ""
2016/10/16 14:21:34 Offset: 6
2016/10/16 14:21:34 Number of candidates found: 35
2016/10/16 14:21:34 Candidates are:
2016/10/16 14:21:34   import 9fans.net/go/acme 
2016/10/16 14:21:34   import 9fans.net/go/plan9 
2016/10/16 14:21:34   import 9fans.net/go/plan9/client 
2016/10/16 14:21:34   import github.com/Bowery/prompt 
2016/10/16 14:21:34   import github.com/alecthomas/template 
2016/10/16 14:21:34   import github.com/alecthomas/template/parse 
2016/10/16 14:21:34   import github.com/alecthomas/units 
2016/10/16 14:21:34   import github.com/dchest/safefile 
2016/10/16 14:21:34   import github.com/fatih/motion/astcontext 
2016/10/16 14:21:34   import github.com/fatih/motion/vim 
2016/10/16 14:21:34   import github.com/golang/lint 
2016/10/16 14:21:34   import github.com/google/shlex 
2016/10/16 14:21:34   import github.com/kardianos/govendor/cliprompt 
2016/10/16 14:21:34   import github.com/kardianos/govendor/context 
2016/10/16 14:21:34   import github.com/kardianos/govendor/help 
2016/10/16 14:21:34   import github.com/kardianos/govendor/internal/pathos 
2016/10/16 14:21:34   import github.com/kardianos/govendor/internal/vfilepath 
2016/10/16 14:21:34   import github.com/kardianos/govendor/internal/vos 
2016/10/16 14:21:34   import github.com/kardianos/govendor/migrate 
2016/10/16 14:21:34   import github.com/kardianos/govendor/pkgspec 
2016/10/16 14:21:34   import github.com/kardianos/govendor/prompt 
2016/10/16 14:21:34   import github.com/kardianos/govendor/run 
2016/10/16 14:21:34   import github.com/kardianos/govendor/vcs 
2016/10/16 14:21:34   import github.com/kardianos/govendor/vendorfile 
2016/10/16 14:21:34   import github.com/kisielk/errcheck/internal/errcheck 
2016/10/16 14:21:34   import github.com/kisielk/gotool 
2016/10/16 14:21:34   import github.com/klauspost/asmfmt 
2016/10/16 14:21:34   import github.com/pkg/errors 
2016/10/16 14:21:34   import github.com/rogpeppe/godef/go/ast 
2016/10/16 14:21:34   import github.com/rogpeppe/godef/go/parser 
2016/10/16 14:21:34   import github.com/rogpeppe/godef/go/printer 
2016/10/16 14:21:34   import github.com/rogpeppe/godef/go/scanner 
2016/10/16 14:21:34   import github.com/rogpeppe/godef/go/token 
2016/10/16 14:21:34   import github.com/rogpeppe/godef/go/types 
2016/10/16 14:21:34   import golang.org/x/tools/go/vcs 
2016/10/16 14:21:34 =======================================================
```

**Comment by nicorevin** [comment] 2016-10-16 14:06
@cskr @nsf for me vim returns what is expected except that it includes non-package vendored imports as well:

<img width="376" alt="2016-10-16 16 54 10" src="https://cloud.githubusercontent.com/assets/2492836/19417906/3bd11ae6-93c1-11e6-9698-147d23919c8a.png">

but gocode returns what you receive in vim:
```
16:52 /tmp/go/18EDE158-972D-4EFC-ADA4-781951F2D183/src/some.domain/username/prjctnm (master) 
$ gocode -f=json -in=main.go autocomplete 70 |jq '.[1][].name' | tr -d '"'
9fans.net/go/acme
9fans.net/go/plan9
9fans.net/go/plan9/client
github.com/alecthomas/template
github.com/alecthomas/template/parse
github.com/alecthomas/units
github.com/fatih/motion/astcontext
github.com/fatih/motion/vim
github.com/golang/lint
github.com/google/shlex
github.com/kisielk/errcheck/internal/errcheck
github.com/kisielk/gotool
github.com/klauspost/asmfmt
github.com/rogpeppe/godef/go/ast
github.com/rogpeppe/godef/go/parser
github.com/rogpeppe/godef/go/printer
github.com/rogpeppe/godef/go/scanner
github.com/rogpeppe/godef/go/token
github.com/rogpeppe/godef/go/types
16:53 /tmp/go/18EDE158-972D-4EFC-ADA4-781951F2D183/src/some.domain/username/prjctnm (master) 
```
```
$ go list ./...
some.domain/username/prjctnm
some.domain/username/prjctnm/keystone
some.domain/username/prjctnm/neutron
some.domain/username/prjctnm/vendor/github.com/mitchellh/goamz/aws
some.domain/username/prjctnm/vendor/github.com/vaughan0/go-ini
```

Moreover:

<img width="298" alt="2016-10-16 17 00 26" src="https://cloud.githubusercontent.com/assets/2492836/19417944/1f5783b8-93c2-11e6-87ec-bb6e207d8aee.png">

but: 

```
2016/10/16 17:00:01 -------------------------------------------------------
2016/10/16 17:00:01 Error parsing input file (outer block):
2016/10/16 17:00:01  5:8: invalid import path: ";githubva"
2016/10/16 17:00:01 Found "fmt" at "/usr/local/Cellar/go/1.7.1/libexec/pkg/darwin_amd64/fmt.a"
2016/10/16 17:00:01 Import path ";githubva" was not resolved
2016/10/16 17:00:01 Gocode's build context is:
2016/10/16 17:00:01  GOROOT: /usr/local/Cellar/go/1.7.1/libexec
2016/10/16 17:00:01  GOPATH: /tmp/go/18EDE158-972D-4EFC-ADA4-781951F2D183
2016/10/16 17:00:01  GOOS: darwin
2016/10/16 17:00:01  GOARCH: amd64
2016/10/16 17:00:01  BzlProjectRoot: ""
2016/10/16 17:00:01  GBProjectRoot: ""
2016/10/16 17:00:01  lib-path: ""
2016/10/16 17:00:01 Offset: 0
2016/10/16 17:00:01 Number of candidates found: 245
```

```
$ gocode -f=json -in=main.go autocomplete 72 |jq '.' | tr -d '"' 
[]```

If I call <C-x><C-o> directly I get what you, @cskr, get 

Seems like it is not `gocode` but `deoplete` who is helping me with completion in this case.

**Comment by cskr** [comment] 2016-10-16 15:17
@nicorevin I see a behaviour similar to yours if I hit `C-x C-o` immediately after `"` without typing "github" first.

**Comment by dvcrn** [comment] 2016-11-07 06:46
Slightly related but I also don't get completion for packages installed by govendor only, not through `go get`

<img width="784" alt="2016-11-07 3 42 39" src="https://cloud.githubusercontent.com/assets/688326/20048596/1ca18aec-a501-11e6-96f7-f1d91343e5e0.png">

In this case, `elastic.` can't get completed. When installing the package through `go get` into my normal $GOPATH, it can complete it without problems

**Comment by nsf** [comment] 2016-11-07 20:28
If I understand correctly govendor works outside of GOPATH which means gocode knows nothing about conventions it uses. Gocode supports official Go vendor directory and `gb` layout if you use `gocode set package-lookup-mode gb`. I only implemented `gb` because I use it. While it works best for my case. I believe we should stick with official Go's vendoring system as close as possible. Because many tools rely on that structure. Using `gb` myself, I've lost access to many of the Go tools (unless I do hacks with setting custom GOPATH).

**Comment by cskr** [comment] 2016-11-08 03:30
@nsf govendor works with the official `vendor` directory.

**Comment by nsf** [comment] 2016-11-08 06:24
I never said it doesn't use vendor, I said it operates outside of user set GOPATH.

**Comment by cskr** [comment] 2016-11-08 08:20
Sorry, I probably misunderstood your comment. I still don't understand what you meant by, "operates outside of user set GOPATH".

govendor populates the standard `vendor` directory with dependencies. It is more like gvt and glide than gb.

**Comment by reorx** [comment] 2016-11-08 08:23
Is your project that use govendor under your GOPATH?
Chandra Sekar S <notifications@github.com>于2016年11月8日 周二下午4:20写道：

**Comment by nsf** [comment] 2016-11-08 09:05
> Sorry, I probably misunderstood your comment. I still don't understand what you meant by, "operates outside of user set GOPATH".

Yes, it's my mistake actually. Sorry. Govendor suggests that it should operate within GOPATH. 

But in this case there is no reason why gocode wouldn't pick up the completions. Unless you haven't compiled the code via `go install`.

@dvcrn What do you mean by "packages installed by govendor only"? Did you actually run "govendor install"?

**Comment by dvcrn** [comment] 2016-11-09 01:21
@nsf I used `govendor fetch` which just installs something into the `vendor/` directory + updates the vendor.json. 

I tested just now again with a random package from gopkg.in (`govendor fetch gopkg.in/pipe.v2`) and gocode can't complete it. I tested with a couple different editors to make sure it's not something in their usage of gocode. 

Then I also tried to remove `elastic` from my gopath (from `$GO/src` and `$GO/pkg`) and the completion stopped working again, even though it is still available under `vendor/gopkg.in/...`

**Comment by nsf** [comment] 2016-11-09 05:57
You missed what I said. You need to compile the lib for gocode to pick it up. Gocode doesn't work with source files.

**Comment by nsf** [comment] 2016-11-09 06:01
And sorry for me being confusing. I probably should mention it somewhere in the README.

**Comment by ashb** [comment] 2016-11-11 12:27
Does this mean that if two different projects(/packages) vendor different versions of the same third party then only the last one to be compiled into a package will work correctly for completions?

**Comment by nsf** [comment] 2016-11-11 12:36
@ashb gocode should use full paths as unique package identifiers, so these will be seen as two different packages.. at least it should be this way

**Comment by ashb** [comment] 2016-11-11 12:44
Ah yes, I think `go install ./...` was what I needed to run (I thought I had, but i guess not, or not with that exact arg) and it produces GOPATH/pkg/github.com/ashb/project/vendor/....

So sorry for the noise, this is working for me now (just need to update the version bundled in ycmd.

Thanks for the awesome project!

**Comment by dvcrn** [comment] 2016-11-11 12:49
@nsf Interesting, that explains a lot! Indeed, once the dependency is compiled, gocode completes it just fine. I didn't know that. My issues is resolved with this 👍 

Slightly related with a risk of getting too much offtopic, I noticed that the same problem happens for new files in the same project, files that got added later and haven't been compiled yet. What is the "go-to" solution for this? Just use something that auto compiles the project?

**Comment by nsf** [comment] 2016-11-11 12:57
@dvcrn For currently edited package gocode uses source files and if it doesn't pick up new files it's a bug, but if you add a file into a separate package and use it from another package, that separate package should be compiled first. Gocode has `autobuild` feature (see README.md), but I wouldn't guarantee it would work. All it does is it runs `go install` before autocompletion. You can also use third party FS watcher which compiles stuff for you. In my opinion if you do something that requires you to jump from one package to another, you do it wrong. But that's only my opinion, I understand people have different workflows. One day gocode will parse source files, but I can't tell when it happens, maybe next year, maybe even later. Once I had a plenty of time to work on gocode, now I don't have time at all and if I have some, I spend it on different projects of mine, often not even related to Go.

**Closed** 2017-03-04 15:10 UTC
Labels: Bug
